[package]
name = "gas-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = { version = "2.0.109", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.103"
darling = "0.21.3"
